<?php
/**
 * Created by PhpStorm.
 * User: dtulp
 * Date: 19-2-2018
 * Time: 14:24.
 */

namespace Tests\Unit;

use Illuminate\Http\Request;
use Swis\JsonApi\Server\Exceptions\ContentTypeNotSupportedException;
use Swis\JsonApi\Server\Http\Middleware\InspectContentType;
use Tests\TestCase;

class InspectContentTypeTest extends TestCase
{
    /** @var Request */
    protected $request;
    /** @var InspectContentType */
    protected $middleware;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->request = Request::create('http://example.com/admin', 'GET');
        $this->middleware = new InspectContentType();
    }

    /**
     * @test
     *
     * @throws ContentTypeNotSupportedException
     */
    public function itThrowsContentTypeNotSupportedException()
    {
        $this->expectException(ContentTypeNotSupportedException::class);
        $this->middleware->handle($this->request, function () {
        });
    }

    /**
     * @test
     *
     * @throws ContentTypeNotSupportedException
     */
    public function itDoesNotThrowContentTypeNotSupportedException()
    {
        $this->request->headers->set('Content-Type', 'application/vnd.api+json');
        $response = $this->middleware->handle($this->request, function () {
        });
        $this->assertEquals($response, null);
    }
}
